# Generated by Django 3.1.6 on 2021-02-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('logo', models.URLField(default='https://place-hold.it/100x60', null=True)),
                ('description', models.TextField()),
                ('employee_count', models.IntegerField()),
            ],
        ),
    ]
