# Generated by Django 3.1.6 on 2021-02-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210218_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company_images/130x80.gif', upload_to='company_images'),
        ),
    ]
