# Generated by Django 3.1.6 on 2021-02-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20210223_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(),
        ),
    ]
